export const nflSchedule2022to2023 = [
  {
    date: '2022-09-08',
    time: '8:20 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-09-11',
    time: '1:00 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2022-09-11',
    time: '4:25 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-09-11',
    time: '4:25 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-09-11',
    time: '4:25 PM',
    awayTeam: 'New York Giants',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2022-09-11',
    time: '4:25 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2022-09-11',
    time: '8:20 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-09-12',
    time: '8:20 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2022-09-15',
    time: '8:15 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2022-09-18',
    time: '1:00 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-09-18',
    time: '1:00 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-09-18',
    time: '1:00 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2022-09-18',
    time: '1:00 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-09-18',
    time: '1:00 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-09-18',
    time: '1:00 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2022-09-18',
    time: '1:00 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2022-09-18',
    time: '4:05 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-09-18',
    time: '4:05 PM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-09-18',
    time: '4:25 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-09-18',
    time: '4:25 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2022-09-18',
    time: '4:25 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2022-09-18',
    time: '8:20 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2022-09-19',
    time: '7:15 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2022-09-19',
    time: '8:30 PM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2022-09-22',
    time: '8:15 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2022-09-25',
    time: '1:00 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2022-09-25',
    time: '4:05 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2022-09-25',
    time: '4:25 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-09-25',
    time: '4:25 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2022-09-25',
    time: '4:25 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-09-25',
    time: '8:20 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2022-09-26',
    time: '8:15 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-09-29',
    time: '8:15 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2022-10-02',
    time: '9:30 AM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2022-10-02',
    time: '1:00 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2022-10-02',
    time: '4:05 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-10-02',
    time: '4:25 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2022-10-02',
    time: '4:25 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2022-10-02',
    time: '8:20 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-10-03',
    time: '8:15 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-10-06',
    time: '8:15 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2022-10-09',
    time: '9:30 AM',
    awayTeam: 'New York Giants',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-10-09',
    time: '1:00 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2022-10-09',
    time: '4:05 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-10-09',
    time: '4:25 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-10-09',
    time: '4:25 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-10-09',
    time: '8:20 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2022-10-10',
    time: '8:15 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2022-10-13',
    time: '8:15 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-10-16',
    time: '1:00 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2022-10-16',
    time: '4:05 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-10-16',
    time: '4:05 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2022-10-16',
    time: '4:25 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2022-10-16',
    time: '8:20 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2022-10-17',
    time: '8:15 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2022-10-20',
    time: '8:15 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-10-23',
    time: '1:00 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-10-23',
    time: '1:00 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2022-10-23',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-10-23',
    time: '1:00 PM',
    awayTeam: 'New York Giants',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2022-10-23',
    time: '1:00 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2022-10-23',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2022-10-23',
    time: '1:00 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2022-10-23',
    time: '4:05 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2022-10-23',
    time: '4:05 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2022-10-23',
    time: '4:25 PM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2022-10-23',
    time: '4:25 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-10-23',
    time: '8:20 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2022-10-24',
    time: '8:15 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2022-10-27',
    time: '8:15 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-10-30',
    time: '9:30 AM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2022-10-30',
    time: '1:00 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2022-10-30',
    time: '1:00 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-10-30',
    time: '1:00 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-10-30',
    time: '1:00 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-10-30',
    time: '1:00 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-10-30',
    time: '1:00 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-10-30',
    time: '1:00 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2022-10-30',
    time: '4:05 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2022-10-30',
    time: '4:25 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2022-10-30',
    time: '4:25 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-10-30',
    time: '4:25 PM',
    awayTeam: 'New York Giants',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2022-10-30',
    time: '8:20 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2022-10-31',
    time: '8:15 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-11-03',
    time: '8:15 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-11-06',
    time: '1:00 PM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2022-11-06',
    time: '4:05 PM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-11-06',
    time: '4:25 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-11-06',
    time: '8:20 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2022-11-07',
    time: '8:15 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-11-10',
    time: '8:15 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-11-13',
    time: '9:30 AM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-11-13',
    time: '1:00 PM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2022-11-13',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-11-13',
    time: '1:00 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2022-11-13',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2022-11-13',
    time: '1:00 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-11-13',
    time: '1:00 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2022-11-13',
    time: '1:00 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2022-11-13',
    time: '4:05 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2022-11-13',
    time: '4:25 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2022-11-13',
    time: '4:25 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-11-13',
    time: '8:20 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-11-14',
    time: '8:15 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2022-11-17',
    time: '8:15 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-11-20',
    time: '1:00 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2022-11-20',
    time: '4:05 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2022-11-20',
    time: '4:25 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-11-20',
    time: '4:25 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2022-11-20',
    time: '8:20 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2022-11-21',
    time: '8:15 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-11-24',
    time: '12:30 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-11-24',
    time: '4:30 PM',
    awayTeam: 'New York Giants',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-11-24',
    time: '8:20 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-11-27',
    time: '1:00 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-11-27',
    time: '1:00 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-11-27',
    time: '1:00 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2022-11-27',
    time: '1:00 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2022-11-27',
    time: '1:00 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-11-27',
    time: '1:00 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2022-11-27',
    time: '1:00 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2022-11-27',
    time: '4:05 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-11-27',
    time: '4:05 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2022-11-27',
    time: '4:25 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2022-11-27',
    time: '4:25 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-11-27',
    time: '8:20 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2022-11-28',
    time: '8:15 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2022-12-01',
    time: '8:15 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2022-12-04',
    time: '1:00 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2022-12-04',
    time: '4:05 PM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-12-04',
    time: '4:05 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-12-04',
    time: '4:25 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2022-12-04',
    time: '4:25 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2022-12-04',
    time: '8:20 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-12-05',
    time: '8:15 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-12-08',
    time: '8:15 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-12-11',
    time: '1:00 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2022-12-11',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2022-12-11',
    time: '1:00 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-12-11',
    time: '1:00 PM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2022-12-11',
    time: '1:00 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'New York Giants',
  },
  {
    date: '2022-12-11',
    time: '1:00 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2022-12-11',
    time: '1:00 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2022-12-11',
    time: '4:05 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2022-12-11',
    time: '4:25 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2022-12-11',
    time: '4:25 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-12-11',
    time: '8:20 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2022-12-12',
    time: '8:15 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-12-15',
    time: '8:15 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-12-18',
    time: '1:00 PM',
    awayTeam: 'New York Giants',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2022-12-18',
    time: '4:05 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2022-12-18',
    time: '4:25 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2022-12-18',
    time: '4:25 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2022-12-18',
    time: '8:20 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2022-12-19',
    time: '8:15 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2022-12-22',
    time: '8:15 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'New York Jets',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'Carolina Panthers',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'Cleveland Browns',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'Seattle Seahawks',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'New York Giants',
    homeTeam: 'Minnesota Vikings',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'Cincinnati Bengals',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2022-12-24',
    time: '1:00 PM',
    awayTeam: 'Atlanta Falcons',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2022-12-24',
    time: '4:05 PM',
    awayTeam: 'Washington Commanders',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2022-12-24',
    time: '4:25 PM',
    awayTeam: 'Philadelphia Eagles',
    homeTeam: 'Dallas Cowboys',
  },
  {
    date: '2022-12-24',
    time: '8:15 PM',
    awayTeam: 'Las Vegas Raiders',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2022-12-25',
    time: '1:00 PM',
    awayTeam: 'Green Bay Packers',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2022-12-25',
    time: '4:30 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Los Angeles Rams',
  },
  {
    date: '2022-12-25',
    time: '8:20 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'Arizona Cardinals',
  },
  {
    date: '2022-12-26',
    time: '8:15 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2022-12-29',
    time: '8:15 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'Tennessee Titans',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Chicago Bears',
    homeTeam: 'Detroit Lions',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Jacksonville Jaguars',
    homeTeam: 'Houston Texans',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Denver Broncos',
    homeTeam: 'Kansas City Chiefs',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Miami Dolphins',
    homeTeam: 'New England Patriots',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Indianapolis Colts',
    homeTeam: 'New York Giants',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'New Orleans Saints',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Pittsburgh Steelers',
    homeTeam: 'Baltimore Ravens',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'Tampa Bay Buccaneers',
  },
  {
    date: '2023-01-01',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Washington Commanders',
  },
  {
    date: '2023-01-01',
    time: '4:05 PM',
    awayTeam: 'San Francisco 49ers',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2023-01-01',
    time: '4:05 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2023-01-01',
    time: '4:25 PM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2023-01-01',
    time: '8:20 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'Los Angeles Chargers',
  },
  {
    date: '2023-01-02',
    time: '8:30 PM',
    awayTeam: 'Buffalo Bills',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Tampa Bay Buccaneers',
    homeTeam: 'Atlanta Falcons',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'New England Patriots',
    homeTeam: 'Buffalo Bills',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Minnesota Vikings',
    homeTeam: 'Chicago Bears',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Baltimore Ravens',
    homeTeam: 'Cincinnati Bengals',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Houston Texans',
    homeTeam: 'Indianapolis Colts',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Los Angeles Chargers',
    homeTeam: 'Denver Broncos',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Detroit Lions',
    homeTeam: 'Green Bay Packers',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Tennessee Titans',
    homeTeam: 'Jacksonville Jaguars',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'New York Jets',
    homeTeam: 'Miami Dolphins',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Carolina Panthers',
    homeTeam: 'New Orleans Saints',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'New York Giants',
    homeTeam: 'Philadelphia Eagles',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Cleveland Browns',
    homeTeam: 'Pittsburgh Steelers',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Kansas City Chiefs',
    homeTeam: 'Las Vegas Raiders',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Los Angeles Rams',
    homeTeam: 'Seattle Seahawks',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Arizona Cardinals',
    homeTeam: 'San Francisco 49ers',
  },
  {
    date: '2023-01-08',
    time: '1:00 PM',
    awayTeam: 'Dallas Cowboys',
    homeTeam: 'Washington Commanders',
  },
];
